name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天北京时间早上 8 点自动运行
  workflow_dispatch:      # 允许手动在 Actions 页面点击按钮运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with Upstream
        uses: aormsby/fork-sync-upstream@v3.4.1
        with:
          target_sync_branch: main        # 你仓库的分支名（通常是 main 或 master）
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_sync_branch: main      # 上游仓库的分支名
          upstream_sync_repo: vudovn/antigravity-kit
